import type {
  ApiState,
  ApiDocumentType,
  ApiDocument,
  ApiReconciliationRunResponse,
  ApiReconciliationCase,
  AuthorityDashboardStats,
  CaseQueueItem,
  AuthorityCaseDetailFull,
  FilterOptionsResponse,
  ApiCadastralParcel,
  ApiCadastralGeoJSONCollection,
  ApiLandRecordSummary,
} from './api';

export const FALLBACK_STATES: ApiState[] = [
  { id: 1, name: 'Maharashtra', code: 'MH', is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 2, name: 'Karnataka', code: 'KA', is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 3, name: 'Gujarat', code: 'GJ', is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 4, name: 'Madhya Pradesh', code: 'MP', is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 5, name: 'Uttar Pradesh', code: 'UP', is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
];

export const FALLBACK_DOC_TYPES: ApiDocumentType[] = [
  { id: 1, name: 'Sale Deed (खरेदीखत)', code: 'SALE_DEED', description: 'Registered instrument of conveyance', state_id: 1, is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 2, name: 'Mutation Record (फेरफार नोंद)', code: 'MUTATION_RECORD', description: 'Revenue ledger change record', state_id: 1, is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 3, name: '7/12 Extract (सातबारा उतारा)', code: '7_12_EXTRACT', description: 'Record of rights and crop extract', state_id: 1, is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 4, name: 'Registration Document', code: 'REGISTRATION_DOC', description: 'Sub-registrar office registration document', state_id: null, is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
  { id: 5, name: 'Generic Land Record', code: 'GENERIC_LAND_RECORD', description: 'Standardized generic cadastral document', state_id: null, is_active: true, created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z' },
];

export const FALLBACK_DOCUMENTS: ApiDocument[] = [
  {
    id: 1,
    case_id: 1,
    demo_owner_type: 'DEMO_CITIZEN',
    file_name: 'Sale_Deed_Doc_142_3.pdf',
    file_path: 'storage/demo/Sale_Deed_Doc_142_3.pdf',
    file_type: 'application/pdf',
    file_size: 245800,
    state_id: 1,
    document_type_id: 1,
    language: 'en',
    status: 'COMPLETED',
    quality_status: 'GOOD',
    page_count: 3,
    uploaded_at: '2026-09-20T10:00:00Z',
    created_at: '2026-09-20T10:00:00Z',
    updated_at: '2026-09-20T10:00:00Z',
    document_type: FALLBACK_DOC_TYPES[0],
    state: FALLBACK_STATES[0],
  },
  {
    id: 2,
    case_id: 1,
    demo_owner_type: 'DEMO_CITIZEN',
    file_name: 'Ferfar_Mutation_Entry_894.pdf',
    file_path: 'storage/demo/Ferfar_Mutation_Entry_894.pdf',
    file_type: 'application/pdf',
    file_size: 184200,
    state_id: 1,
    document_type_id: 2,
    language: 'mr',
    status: 'COMPLETED',
    quality_status: 'ACCEPTABLE',
    page_count: 2,
    uploaded_at: '2026-09-20T10:05:00Z',
    created_at: '2026-09-20T10:05:00Z',
    updated_at: '2026-09-20T10:05:00Z',
    document_type: FALLBACK_DOC_TYPES[1],
    state: FALLBACK_STATES[0],
  },
  {
    id: 3,
    case_id: 1,
    demo_owner_type: 'DEMO_CITIZEN',
    file_name: '7_12_Extract_Gat_142_3.pdf',
    file_path: 'storage/demo/7_12_Extract_Gat_142_3.pdf',
    file_type: 'application/pdf',
    file_size: 162000,
    state_id: 1,
    document_type_id: 3,
    language: 'mr',
    status: 'COMPLETED',
    quality_status: 'GOOD',
    page_count: 1,
    uploaded_at: '2026-09-20T10:10:00Z',
    created_at: '2026-09-20T10:10:00Z',
    updated_at: '2026-09-20T10:10:00Z',
    document_type: FALLBACK_DOC_TYPES[2],
    state: FALLBACK_STATES[0],
  },
];

export const FALLBACK_RECONCILIATION_RUN: ApiReconciliationRunResponse = {
  case_id: 1,
  case_number: 'CASE-MH-2026-001',
  status: 'UNDER_VERIFICATION',
  risk_level: 'HIGH',
  documents_count: 3,
  documents: [
    {
      id: 1,
      file_name: 'Sale_Deed_Doc_142_3.pdf',
      document_type_name: 'Sale Deed',
      document_type_code: 'SALE_DEED',
      file_size: 245800,
      language: 'en',
      quality_status: 'GOOD',
    },
    {
      id: 2,
      file_name: 'Ferfar_Mutation_Entry_894.pdf',
      document_type_name: 'Ferfar / Mutation Record',
      document_type_code: 'MUTATION_RECORD',
      file_size: 184200,
      language: 'mr',
      quality_status: 'ACCEPTABLE',
    },
    {
      id: 3,
      file_name: '7_12_Extract_Gat_142_3.pdf',
      document_type_name: '7/12 Extract',
      document_type_code: '7_12_EXTRACT',
      file_size: 162000,
      language: 'mr',
      quality_status: 'GOOD',
    },
  ],
  summary_stats: {
    total_fields: 6,
    exact_matches: 4,
    likely_matches: 1,
    minor_differences: 0,
    conflicts: 1,
    missing: 0,
    needs_review: 0,
  },
  risk_assessment: {
    overall_risk: 'CRITICAL',
    risk_score: 78,
    risk_factors: [
      'Owner name spelling mismatch in Mutation Record (Rakesh Kumar vs Rajesh Kumar)',
      'Cross-language phonetic transliteration uncertainty in Marathi revenue ledger',
    ],
    risk_dimensions: {
      owner_conflict: {
        name: 'Cadastral Title Integrity',
        status: 'FAIL',
        severity: 'CRITICAL',
        score_impact: 45,
        explanation: 'Primary grantee is recorded as Rajesh Kumar in Registered Sale Deed but mutated as Rakesh Kumar in Form 6 ledger.',
      },
      area_discrepancy: {
        name: 'Spatial Area Delta',
        status: 'PASS',
        severity: 'LOW',
        score_impact: 0,
        explanation: 'Extracted area across all 3 documents consistently normalizes to 0.8090 Hectares (2.00 Acres).',
      },
      survey_continuity: {
        name: 'Survey Parcel Continuity',
        status: 'PASS',
        severity: 'LOW',
        score_impact: 0,
        explanation: 'Gat No. 142/3 is referenced across all legal chain instruments.',
      },
      encumbrance_status: {
        name: 'Encumbrance & Charge Audit',
        status: 'WARN',
        severity: 'MEDIUM',
        score_impact: 15,
        explanation: 'Bank of Maharashtra crop loan charge recorded on 7/12 extract requires NOC verification.',
      },
      ocr_extraction_confidence: {
        name: 'OCR & Vision Confidence',
        status: 'PASS',
        severity: 'LOW',
        score_impact: 5,
        explanation: 'Multi-lingual optical character confidence exceeds 96.8% across Devanagari and Latin scripts.',
      },
      legal_chain_continuity: {
        name: 'Chain of Title Continuity',
        status: 'WARN',
        severity: 'MEDIUM',
        score_impact: 13,
        explanation: 'Requires clerical rectification of spelling discrepancy under Maharashtra Land Revenue Code Section 155.',
      },
    },
    summary_explanation: 'High Title Mismatch Risk flagged: 1 Critical Owner Name divergence between Conveyance Deed and Mutation entry requires administrative clerical correction.',
  },
  fields: [
    {
      field_key: 'owner_name',
      field_label: 'Owner Name',
      category: 'PARTY',
      status: 'CONFLICT',
      severity: 'CRITICAL',
      operational_risk: 'Critical',
      extraction_confidence_level: 'High',
      explanation: 'Owner Name differs across instruments: Sale Deed ("Rajesh Kumar") vs Mutation Record ("Rakesh Kumar") vs 7/12 Extract ("राजेश कुमार")',
      what: 'Sale Deed registers "Rajesh Kumar", Mutation Record lists "Rakesh Kumar", and 7/12 Extract reflects "राजेश कुमार".',
      why: 'Clerical typo in Village Form 6 handwritten ledger entry by Talathi clerk during manual entry transcribing from Sale Deed REG-2018-74921.',
      where: [
        {
          doc_id: 1,
          doc_title: 'Sale Deed',
          file_name: 'Sale_Deed_Doc_142_3.pdf',
          page_number: 1,
          source_text: 'PURCHASER: SHRI RAJESH KUMAR s/o Rameshwar Kumar',
          bounding_box: [0.32, 0.08, 0.38, 0.92],
          confidence: 0.98,
          extraction_confidence_level: 'High',
        },
        {
          doc_id: 2,
          doc_title: 'Ferfar / Mutation Record',
          file_name: 'Ferfar_Mutation_Entry_894.pdf',
          page_number: 1,
          source_text: 'नवीन खरेदीदार: श्री राकेश कुमार (Rakesh Kumar)',
          bounding_box: [0.28, 0.18, 0.35, 0.75],
          confidence: 0.96,
          extraction_confidence_level: 'High',
        },
        {
          doc_id: 3,
          doc_title: '7/12 Extract',
          file_name: '7_12_Extract_Gat_142_3.pdf',
          page_number: 1,
          source_text: 'खातेदार: राजेश कुमार (Rajesh Kumar)',
          bounding_box: [0.22, 0.52, 0.30, 0.92],
          confidence: 0.99,
          extraction_confidence_level: 'High',
        },
      ],
      doc_values: [
        {
          doc_id: 1,
          file_name: 'Sale_Deed_Doc_142_3.pdf',
          doc_type_name: 'Sale Deed',
          raw_value: 'Rajesh Kumar',
          normalized_value: 'Rajesh Kumar',
          page_number: 1,
          bounding_box: [0.32, 0.08, 0.38, 0.92],
          source_text: 'PURCHASER: SHRI RAJESH KUMAR',
          confidence: 0.98,
          extraction_confidence_level: 'High',
        },
        {
          doc_id: 2,
          file_name: 'Ferfar_Mutation_Entry_894.pdf',
          doc_type_name: 'Ferfar / Mutation Record',
          raw_value: 'Rakesh Kumar',
          normalized_value: 'Rakesh Kumar',
          page_number: 1,
          bounding_box: [0.28, 0.18, 0.35, 0.75],
          source_text: 'नवीन खरेदीदार: श्री राकेश कुमार',
          confidence: 0.96,
          extraction_confidence_level: 'High',
        },
        {
          doc_id: 3,
          file_name: '7_12_Extract_Gat_142_3.pdf',
          doc_type_name: '7/12 Extract',
          raw_value: 'राजेश कुमार',
          normalized_value: 'Rajesh Kumar',
          page_number: 1,
          bounding_box: [0.22, 0.52, 0.30, 0.92],
          source_text: 'खातेदार: राजेश कुमार',
          confidence: 0.99,
          extraction_confidence_level: 'High',
        },
      ],
    },
    {
      field_key: 'survey_number',
      field_label: 'Survey / Gat Number',
      category: 'PARCEL',
      status: 'EXACT_MATCH',
      severity: 'NONE',
      operational_risk: 'Low',
      extraction_confidence_level: 'High',
      explanation: 'Survey / Gat number 142/3 is congruent across all 3 documents.',
      what: 'All records identify Land Gat No. 142/3 in Wagholi, Haveli, Pune.',
      why: 'Continuous cadastral parcel identification maintained accurately across deed, mutation, and 7/12 extract.',
      where: [
        {
          doc_id: 1,
          doc_title: 'Sale Deed',
          file_name: 'Sale_Deed_Doc_142_3.pdf',
          page_number: 1,
          source_text: 'Gat 142/3 Wagholi',
          bounding_box: [0.44, 0.08, 0.54, 0.28],
          confidence: 0.99,
          extraction_confidence_level: 'High',
        },
        {
          doc_id: 3,
          doc_title: '7/12 Extract',
          file_name: '7_12_Extract_Gat_142_3.pdf',
          page_number: 1,
          source_text: 'भूमापन क्रमांक / गट क्रमांक: 142/3',
          bounding_box: [0.22, 0.08, 0.30, 0.35],
          confidence: 0.99,
          extraction_confidence_level: 'High',
        },
      ],
      doc_values: [
        { doc_id: 1, file_name: 'Sale_Deed_Doc_142_3.pdf', doc_type_name: 'Sale Deed', raw_value: '142/3', normalized_value: '142/3', confidence: 0.99, extraction_confidence_level: 'High' },
        { doc_id: 2, file_name: 'Ferfar_Mutation_Entry_894.pdf', doc_type_name: 'Ferfar / Mutation Record', raw_value: '१४२/३', normalized_value: '142/3', confidence: 0.98, extraction_confidence_level: 'High' },
        { doc_id: 3, file_name: '7_12_Extract_Gat_142_3.pdf', doc_type_name: '7/12 Extract', raw_value: '142/3', normalized_value: '142/3', confidence: 0.99, extraction_confidence_level: 'High' },
      ],
    },
    {
      field_key: 'area',
      field_label: 'Total Land Area',
      category: 'SPATIAL',
      status: 'EXACT_MATCH',
      severity: 'NONE',
      operational_risk: 'Low',
      extraction_confidence_level: 'High',
      explanation: 'Area normalizes perfectly: 2.00 Acres = 0.8090 Hectares (0% delta, 0.00% variance).',
      what: 'Sale Deed records "2.00 Acres", Mutation notes "0.809 हेक्टर", 7/12 Extract specifies "0.8090 हेक्टर".',
      why: 'Standard Maharashtra revenue conversion formula (1 Acre = 0.404686 Hectares) yields exact arithmetic match.',
      where: [
        {
          doc_id: 1,
          doc_title: 'Sale Deed',
          file_name: 'Sale_Deed_Doc_142_3.pdf',
          page_number: 1,
          source_text: 'TOTAL AREA: 2.00 Acres (0.809 Hectares)',
          bounding_box: [0.44, 0.28, 0.54, 0.48],
          confidence: 0.97,
          extraction_confidence_level: 'High',
        },
        {
          doc_id: 3,
          doc_title: '7/12 Extract',
          file_name: '7_12_Extract_Gat_142_3.pdf',
          page_number: 1,
          source_text: 'एकूण क्षेत्र: 0.8090 हेक्टर',
          bounding_box: [0.32, 0.08, 0.42, 0.45],
          confidence: 0.98,
          extraction_confidence_level: 'High',
        },
      ],
      doc_values: [
        { doc_id: 1, file_name: 'Sale_Deed_Doc_142_3.pdf', doc_type_name: 'Sale Deed', raw_value: '2.00 Acres', normalized_value: '0.809 Hectares', confidence: 0.97, extraction_confidence_level: 'High' },
        { doc_id: 2, file_name: 'Ferfar_Mutation_Entry_894.pdf', doc_type_name: 'Ferfar / Mutation Record', raw_value: '२.०० एकर (०.८०९ हेक्टर)', normalized_value: '0.809 Hectares', confidence: 0.95, extraction_confidence_level: 'High' },
        { doc_id: 3, file_name: '7_12_Extract_Gat_142_3.pdf', doc_type_name: '7/12 Extract', raw_value: '0.8090 हेक्टर', normalized_value: '0.809 Hectares', confidence: 0.98, extraction_confidence_level: 'High' },
      ],
      area_comparison: {
        baseline_doc: 'Sale Deed (Doc 1)',
        baseline_hectares: 0.809,
        max_difference_pct: 0,
        tolerance_pct: 1.0,
        status: 'EXACT_MATCH',
        explanation: 'Area across all 3 documents converts precisely to 0.8090 Hectares (2.00 Acres).',
        items: [
          { doc_id: 1, doc_title: 'Sale Deed', original: '2.00 Acres', numeric_value: 2.0, unit: 'Acre', normalized_hectares: 0.809, normalized_sq_meters: 8090, difference_hectares: 0, difference_pct: 0, tolerance_pct: 1.0, status: 'EXACT_MATCH' },
          { doc_id: 2, doc_title: 'Ferfar / Mutation Record', original: '०.८०९ हेक्टर', numeric_value: 0.809, unit: 'Hectare', normalized_hectares: 0.809, normalized_sq_meters: 8090, difference_hectares: 0, difference_pct: 0, tolerance_pct: 1.0, status: 'EXACT_MATCH' },
          { doc_id: 3, doc_title: '7/12 Extract', original: '0.8090 हेक्टर', numeric_value: 0.809, unit: 'Hectare', normalized_hectares: 0.809, normalized_sq_meters: 8090, difference_hectares: 0, difference_pct: 0, tolerance_pct: 1.0, status: 'EXACT_MATCH' },
        ],
      },
    },
    {
      field_key: 'village',
      field_label: 'Village Name',
      category: 'GEOGRAPHIC',
      status: 'EXACT_MATCH',
      severity: 'NONE',
      operational_risk: 'Low',
      extraction_confidence_level: 'High',
      explanation: 'Village Wagholi (वाघोली) confirmed across all documents.',
      doc_values: [
        { doc_id: 1, file_name: 'Sale_Deed_Doc_142_3.pdf', doc_type_name: 'Sale Deed', raw_value: 'Wagholi', normalized_value: 'Wagholi', confidence: 0.99 },
        { doc_id: 2, file_name: 'Ferfar_Mutation_Entry_894.pdf', doc_type_name: 'Ferfar / Mutation Record', raw_value: 'वाघोली', normalized_value: 'Wagholi', confidence: 0.99 },
        { doc_id: 3, file_name: '7_12_Extract_Gat_142_3.pdf', doc_type_name: '7/12 Extract', raw_value: 'वाघोली', normalized_value: 'Wagholi', confidence: 0.99 },
      ],
    },
    {
      field_key: 'taluka_tehsil',
      field_label: 'Taluka / Tehsil',
      category: 'GEOGRAPHIC',
      status: 'EXACT_MATCH',
      severity: 'NONE',
      operational_risk: 'Low',
      extraction_confidence_level: 'High',
      explanation: 'Taluka Haveli (हवेली) confirmed across all documents.',
      doc_values: [
        { doc_id: 1, file_name: 'Sale_Deed_Doc_142_3.pdf', doc_type_name: 'Sale Deed', raw_value: 'Haveli', normalized_value: 'Haveli', confidence: 0.99 },
        { doc_id: 2, file_name: 'Ferfar_Mutation_Entry_894.pdf', doc_type_name: 'Ferfar / Mutation Record', raw_value: 'हवेली', normalized_value: 'Haveli', confidence: 0.99 },
        { doc_id: 3, file_name: '7_12_Extract_Gat_142_3.pdf', doc_type_name: '7/12 Extract', raw_value: 'हवेली', normalized_value: 'Haveli', confidence: 0.99 },
      ],
    },
    {
      field_key: 'district',
      field_label: 'District',
      category: 'GEOGRAPHIC',
      status: 'EXACT_MATCH',
      severity: 'NONE',
      operational_risk: 'Low',
      extraction_confidence_level: 'High',
      explanation: 'District Pune (पुणे) confirmed across all instruments.',
      doc_values: [
        { doc_id: 1, file_name: 'Sale_Deed_Doc_142_3.pdf', doc_type_name: 'Sale Deed', raw_value: 'Pune', normalized_value: 'Pune', confidence: 0.99 },
        { doc_id: 2, file_name: 'Ferfar_Mutation_Entry_894.pdf', doc_type_name: 'Ferfar / Mutation Record', raw_value: 'पुणे', normalized_value: 'Pune', confidence: 0.99 },
        { doc_id: 3, file_name: '7_12_Extract_Gat_142_3.pdf', doc_type_name: '7/12 Extract', raw_value: 'पुणे', normalized_value: 'Pune', confidence: 0.99 },
      ],
    },
  ],
  conflicts: [
    {
      id: 1,
      field_name: 'owner_name',
      severity: 'CRITICAL',
      status: 'OPEN',
      explanation: 'Sale Deed registers "Rajesh Kumar", Ferfar 6 Mutation Record registers "Rakesh Kumar", and 7/12 Extract registers "राजेश कुमार". Typographical clerical error detected in Mutation ledger.',
      documents_involved: ['Sale_Deed_Doc_142_3.pdf', 'Ferfar_Mutation_Entry_894.pdf', '7_12_Extract_Gat_142_3.pdf'],
      values: {
        'Sale Deed': 'Rajesh Kumar',
        'Mutation Record': 'Rakesh Kumar',
        '7/12 Extract': 'राजेश कुमार',
      },
    },
  ],
  executed_at: '2026-09-20T10:15:00Z',
};

export const FALLBACK_CASES: ApiReconciliationCase[] = [
  {
    id: 1,
    case_number: 'CASE-MH-2026-001',
    status: 'UNDER_VERIFICATION',
    risk_level: 'HIGH',
    created_by_type: 'DEMO_CITIZEN',
    created_at: '2026-09-20T10:00:00Z',
    updated_at: '2026-09-20T10:15:00Z',
  },
  {
    id: 2,
    case_number: 'CASE-MH-2026-002',
    status: 'RESOLVED',
    risk_level: 'LOW',
    created_by_type: 'DEMO_CITIZEN',
    created_at: '2026-09-18T09:00:00Z',
    updated_at: '2026-09-19T14:30:00Z',
  },
  {
    id: 3,
    case_number: 'CASE-KA-2026-003',
    status: 'UNDER_VERIFICATION',
    risk_level: 'MEDIUM',
    created_by_type: 'DEMO_CITIZEN',
    created_at: '2026-09-17T11:20:00Z',
    updated_at: '2026-09-18T16:45:00Z',
  },
];

export const FALLBACK_AUTHORITY_STATS: AuthorityDashboardStats = {
  total_cases: 48,
  pending_cases: 14,
  high_priority: 5,
  under_review: 9,
  verified: 22,
  rejected: 2,
  escalated: 1,
  avg_review_time: '4.2 hrs',
};

export const FALLBACK_AUTHORITY_FILTER_OPTIONS: FilterOptionsResponse = {
  states: ['Maharashtra', 'Karnataka', 'Gujarat'],
  districts: ['Pune', 'Nagpur', 'Thane'],
  talukas: ['Haveli', 'Mulshi', 'Shirur'],
  villages: ['Wagholi', 'Kharadi', 'Hinjawadi'],
  document_types: ['SALE_DEED', 'MUTATION_RECORD', '7_12_EXTRACT'],
  risks: ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'],
  statuses: ['UNDER_VERIFICATION', 'RESOLVED', 'REJECTED'],
};

export const FALLBACK_AUTHORITY_CASES: CaseQueueItem[] = [
  {
    id: 1,
    case_number: 'CASE-MH-2026-001',
    citizen_submission_id: 'SUB-2026-9041',
    documents_count: 3,
    document_types: ['Sale Deed', 'Ferfar Record', '7/12 Extract'],
    conflicts_count: 1,
    risk_level: 'HIGH',
    status: 'UNDER_VERIFICATION',
    state: 'Maharashtra',
    district: 'Pune',
    taluka: 'Haveli',
    village: 'Wagholi',
    created_at: '2026-09-20T10:00:00Z',
    assigned_officer: 'Revenue Officer (Tahsil Haveli)',
  },
  {
    id: 2,
    case_number: 'CASE-MH-2026-002',
    citizen_submission_id: 'SUB-2026-8812',
    documents_count: 2,
    document_types: ['Sale Deed', '7/12 Extract'],
    conflicts_count: 0,
    risk_level: 'LOW',
    status: 'RESOLVED',
    state: 'Maharashtra',
    district: 'Pune',
    taluka: 'Mulshi',
    village: 'Hinjawadi',
    created_at: '2026-09-18T09:00:00Z',
    assigned_officer: 'Sub-Divisional Officer',
  },
];

export const FALLBACK_AUTHORITY_CASE_DETAIL: AuthorityCaseDetailFull = {
  id: 1,
  case_number: 'CASE-MH-2026-001',
  citizen_submission_id: 'SUB-2026-9041',
  status: 'UNDER_VERIFICATION',
  risk_level: 'HIGH',
  created_at: '2026-09-20T10:00:00Z',
  updated_at: '2026-09-20T10:15:00Z',
  created_by_type: 'DEMO_CITIZEN',
  assigned_officer: 'Revenue Officer (Tahsil Haveli)',
  jurisdiction: {
    state: 'Maharashtra',
    district: 'Pune',
    taluka: 'Haveli',
    village: 'Wagholi',
    survey_number: '142/3',
  },
  documents: [
    {
      id: 1,
      file_name: 'Sale_Deed_Doc_142_3.pdf',
      document_type_name: 'Sale Deed',
      document_type_code: 'SALE_DEED',
      page_count: 3,
      file_size: 245800,
      language: 'en',
      status: 'COMPLETED',
      quality_status: 'GOOD',
      uploaded_at: '2026-09-20T10:00:00Z',
    },
    {
      id: 2,
      file_name: 'Ferfar_Mutation_Entry_894.pdf',
      document_type_name: 'Ferfar / Mutation Record',
      document_type_code: 'MUTATION_RECORD',
      page_count: 2,
      file_size: 184200,
      language: 'mr',
      status: 'COMPLETED',
      quality_status: 'ACCEPTABLE',
      uploaded_at: '2026-09-20T10:05:00Z',
    },
    {
      id: 3,
      file_name: '7_12_Extract_Gat_142_3.pdf',
      document_type_name: '7/12 Extract',
      document_type_code: '7_12_EXTRACT',
      page_count: 1,
      file_size: 162000,
      language: 'mr',
      status: 'COMPLETED',
      quality_status: 'GOOD',
      uploaded_at: '2026-09-20T10:10:00Z',
    },
  ],
  ocr_transcripts: [
    {
      document_id: 1,
      file_name: 'Sale_Deed_Doc_142_3.pdf',
      page_number: 1,
      ocr_text: 'DEED OF ABSOLUTE SALE. Between Suresh Patel (Vendor) and Rajesh Kumar (Purchaser) for Land Gat 142/3 measuring 2.00 Acres in Wagholi, Pune.',
      confidence: 0.98,
    },
    {
      document_id: 2,
      file_name: 'Ferfar_Mutation_Entry_894.pdf',
      page_number: 1,
      ocr_text: 'महाराष्ट्र शासन महसूल विभाग फेरफार नोंद क्र. ७४२. खरेदीखत दस्त क्र. REG-2018-74921 अन्वये गट नं. १४२/३ क्षेत्र २.०० एकर. नवीन खरेदीदार: श्री राकेश कुमार.',
      confidence: 0.96,
    },
  ],
  extracted_fields: [
    {
      id: 1,
      document_id: 1,
      document_name: 'Sale_Deed_Doc_142_3.pdf',
      field_name: 'owner_name',
      raw_value: 'Rajesh Kumar',
      normalized_value: 'Rajesh Kumar',
      confidence: 0.98,
      page_number: 1,
      status: 'VERIFIED',
    },
    {
      id: 2,
      document_id: 2,
      document_name: 'Ferfar_Mutation_Entry_894.pdf',
      field_name: 'owner_name',
      raw_value: 'Rakesh Kumar',
      normalized_value: 'Rakesh Kumar',
      confidence: 0.96,
      page_number: 1,
      status: 'NEEDS_REVIEW',
    },
  ],
  conflicts: [
    {
      id: 1,
      case_id: 1,
      field_name: 'owner_name',
      severity: 'CRITICAL',
      status: 'OPEN',
      explanation: 'Spelling divergence between Conveyance Deed ("Rajesh Kumar") and Revenue Ledger Mutation Entry ("Rakesh Kumar").',
      documents_involved: 'Sale_Deed_Doc_142_3.pdf, Ferfar_Mutation_Entry_894.pdf',
      values: 'Deed: Rajesh Kumar, Mutation: Rakesh Kumar',
      created_at: '2026-09-20T10:15:00Z',
      resolved_at: null,
    },
  ],
  reconciliation_results: [
    { id: 1, field_name: 'owner_name', status: 'CONFLICT', explanation: 'Owner name mismatch' },
    { id: 2, field_name: 'survey_number', status: 'EXACT_MATCH', explanation: 'Gat 142/3 matches' },
    { id: 3, field_name: 'area', status: 'EXACT_MATCH', explanation: '2.00 Acres matches 0.8090 Hectares' },
  ],
  risk_assessment: {
    overall_risk: 'HIGH',
    risk_score: 78,
    risk_factors: [
      'Owner name spelling mismatch between registered deed and revenue ledger.',
    ],
    extraction_confidence_level: 'High',
  },
  timeline: [
    { timestamp: '2026-09-20T10:00:00Z', user: 'Rajesh Kumar', role: 'Citizen', action: 'UPLOAD', description: 'Citizen submitted land record triad documents.' },
    { timestamp: '2026-09-20T10:05:00Z', user: 'AI Engine', role: 'System', action: 'RECONCILIATION', description: 'AI Reconciler detected Owner Name divergence.' },
    { timestamp: '2026-09-20T10:10:00Z', user: 'Tahsil System', role: 'System', action: 'FLAG_RISK', description: 'High Risk Alert assigned to Tahsil Haveli Officer queue.' },
  ],
};

export const FALLBACK_CADASTRAL_PARCELS: ApiCadastralParcel[] = [
  {
    id: 1,
    parcel_number: 'PARCEL-WAG-142-3',
    survey_number: '142/3',
    gat_number: '142/3',
    village: 'Wagholi',
    tehsil: 'Haveli',
    district: 'Pune',
    state: 'Maharashtra',
    area: 2.0,
    area_unit: 'Acre',
    land_type: 'Agricultural',
    owner_name: 'Rajesh Kumar',
    status: 'VERIFIED',
    confidence: 0.94,
    centroid_lat: 18.5795,
    centroid_lng: 73.9823,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-09-20T10:00:00Z',
  },
  {
    id: 2,
    parcel_number: 'PARCEL-WAG-142-2',
    survey_number: '142/2',
    gat_number: '142/2',
    village: 'Wagholi',
    tehsil: 'Haveli',
    district: 'Pune',
    state: 'Maharashtra',
    area: 1.5,
    area_unit: 'Acre',
    land_type: 'Agricultural',
    owner_name: 'Govind More',
    status: 'VERIFIED',
    confidence: 0.98,
    centroid_lat: 18.5808,
    centroid_lng: 73.9823,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-09-18T00:00:00Z',
  },
];

export const FALLBACK_GEOJSON: ApiCadastralGeoJSONCollection = {
  type: 'FeatureCollection',
  name: 'Wagholi Cadastral Parcels',
  features: [
    {
      type: 'Feature',
      id: 1,
      geometry: {
        type: 'Polygon',
        coordinates: [
          [
            [73.9812, 18.5789],
            [73.9812, 18.5801],
            [73.9835, 18.5801],
            [73.9835, 18.5789],
            [73.9812, 18.5789],
          ],
        ],
      },
      properties: {
        ...FALLBACK_CADASTRAL_PARCELS[0],
        notice: 'Reconciliation under review (Case CASE-MH-2026-001)',
      },
    },
    {
      type: 'Feature',
      id: 2,
      geometry: {
        type: 'Polygon',
        coordinates: [
          [
            [73.9812, 18.5802],
            [73.9812, 18.5815],
            [73.9835, 18.5815],
            [73.9835, 18.5802],
            [73.9812, 18.5802],
          ],
        ],
      },
      properties: {
        ...FALLBACK_CADASTRAL_PARCELS[1],
      },
    },
  ],
};

export const FALLBACK_LAND_RECORDS: ApiLandRecordSummary[] = [
  {
    id: 1,
    owner_name: 'Rajesh Kumar',
    owner_name_native: 'राजेश कुमार',
    survey_number: '142/3',
    gat_number: '142/3',
    village: 'Wagholi',
    taluka_tehsil: 'Haveli',
    district: 'Pune',
    area_value: 2.0,
    area_unit: 'Acre',
    land_type: 'Agricultural',
    registration_number: 'REG-2018-74921',
    mutation_number: '742',
    parcel_status: 'UNDER_VERIFICATION',
    has_name_conflict: true,
    conflicting_names: ['Rajesh Kumar', 'Rakesh Kumar', 'राजेश कुमार'],
    linked_documents_count: 3,
    created_at: '2026-09-20T10:00:00Z',
  },
];
