"""Initial schema

Revision ID: c09a18c3c113
Revises: 
Create Date: 2026-09-12 22:56:06.096836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09a18c3c113'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('created_by_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconciliation_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliation_cases_case_number'), ['case_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_reconciliation_cases_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_cases_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_cases_status'), ['status'], unique=False)

    op.create_table('states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_states_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_states_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_states_name'), ['name'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['reconciliation_cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('conflicts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['reconciliation_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflicts_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflicts_field_name'), ['field_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflicts_id'), ['id'], unique=False)

    op.create_table('document_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_types_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_types_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_types_state_id'), ['state_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipient_type', sa.String(length=50), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['reconciliation_cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)

    op.create_table('reconciliation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['reconciliation_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconciliation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliation_results_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_results_field_name'), ['field_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_results_id'), ['id'], unique=False)

    op.create_table('verification_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('performed_by_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['reconciliation_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_actions_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_actions_id'), ['id'], unique=False)

    op.create_table('verification_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submitted_by_type', sa.String(length=50), nullable=False),
    sa.Column('request_message', sa.Text(), nullable=True),
    sa.Column('authority_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['reconciliation_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_requests_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_requests_id'), ['id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('demo_owner_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('document_type_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('quality_status', sa.String(length=50), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['reconciliation_cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_document_type_id'), ['document_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_state_id'), ['state_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)

    op.create_table('document_pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_pages_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_pages_id'), ['id'], unique=False)

    op.create_table('document_processing_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_processing_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_processing_jobs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_processing_jobs_id'), ['id'], unique=False)

    op.create_table('extracted_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('bounding_box', sa.Text(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracted_fields_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_fields_field_name'), ['field_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_fields_id'), ['id'], unique=False)

    op.create_table('gis_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('survey_number', sa.String(length=100), nullable=True),
    sa.Column('geometry_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['reconciliation_cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gis_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gis_locations_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gis_locations_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gis_locations_id'), ['id'], unique=False)

    op.create_table('land_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('survey_number', sa.String(length=100), nullable=True),
    sa.Column('gat_number', sa.String(length=100), nullable=True),
    sa.Column('khasra_number', sa.String(length=100), nullable=True),
    sa.Column('khata_number', sa.String(length=100), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('taluka_tehsil', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('area_value', sa.Float(), nullable=True),
    sa.Column('area_unit', sa.String(length=50), nullable=True),
    sa.Column('land_type', sa.String(length=100), nullable=True),
    sa.Column('mutation_number', sa.String(length=100), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('document_date', sa.DateTime(), nullable=True),
    sa.Column('mutation_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('land_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_land_records_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_land_records_gat_number'), ['gat_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_land_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_land_records_khasra_number'), ['khasra_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_land_records_khata_number'), ['khata_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_land_records_owner_name'), ['owner_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_land_records_state_id'), ['state_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_land_records_survey_number'), ['survey_number'], unique=False)

    op.create_table('ocr_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_page_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('bounding_boxes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_page_id'], ['document_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ocr_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocr_results_document_page_id'), ['document_page_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ocr_results_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocr_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocr_results_id'))
        batch_op.drop_index(batch_op.f('ix_ocr_results_document_page_id'))

    op.drop_table('ocr_results')
    with op.batch_alter_table('land_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_land_records_survey_number'))
        batch_op.drop_index(batch_op.f('ix_land_records_state_id'))
        batch_op.drop_index(batch_op.f('ix_land_records_owner_name'))
        batch_op.drop_index(batch_op.f('ix_land_records_khata_number'))
        batch_op.drop_index(batch_op.f('ix_land_records_khasra_number'))
        batch_op.drop_index(batch_op.f('ix_land_records_id'))
        batch_op.drop_index(batch_op.f('ix_land_records_gat_number'))
        batch_op.drop_index(batch_op.f('ix_land_records_document_id'))

    op.drop_table('land_records')
    with op.batch_alter_table('gis_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gis_locations_id'))
        batch_op.drop_index(batch_op.f('ix_gis_locations_document_id'))
        batch_op.drop_index(batch_op.f('ix_gis_locations_case_id'))

    op.drop_table('gis_locations')
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_fields_id'))
        batch_op.drop_index(batch_op.f('ix_extracted_fields_field_name'))
        batch_op.drop_index(batch_op.f('ix_extracted_fields_document_id'))

    op.drop_table('extracted_fields')
    with op.batch_alter_table('document_processing_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_processing_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_document_processing_jobs_document_id'))

    op.drop_table('document_processing_jobs')
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_pages_id'))
        batch_op.drop_index(batch_op.f('ix_document_pages_document_id'))

    op.drop_table('document_pages')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_state_id'))
        batch_op.drop_index(batch_op.f('ix_documents_id'))
        batch_op.drop_index(batch_op.f('ix_documents_document_type_id'))
        batch_op.drop_index(batch_op.f('ix_documents_case_id'))

    op.drop_table('documents')
    with op.batch_alter_table('verification_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_requests_id'))
        batch_op.drop_index(batch_op.f('ix_verification_requests_case_id'))

    op.drop_table('verification_requests')
    with op.batch_alter_table('verification_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_actions_id'))
        batch_op.drop_index(batch_op.f('ix_verification_actions_case_id'))

    op.drop_table('verification_actions')
    with op.batch_alter_table('reconciliation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliation_results_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_results_field_name'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_results_case_id'))

    op.drop_table('reconciliation_results')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_case_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('document_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_types_state_id'))
        batch_op.drop_index(batch_op.f('ix_document_types_id'))
        batch_op.drop_index(batch_op.f('ix_document_types_code'))

    op.drop_table('document_types')
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflicts_id'))
        batch_op.drop_index(batch_op.f('ix_conflicts_field_name'))
        batch_op.drop_index(batch_op.f('ix_conflicts_case_id'))

    op.drop_table('conflicts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_case_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_states_name'))
        batch_op.drop_index(batch_op.f('ix_states_id'))
        batch_op.drop_index(batch_op.f('ix_states_code'))

    op.drop_table('states')
    with op.batch_alter_table('reconciliation_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliation_cases_status'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_cases_risk_level'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_cases_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_cases_case_number'))

    op.drop_table('reconciliation_cases')
    # ### end Alembic commands ###
